In [2]:
pip install numpy


     -------------------------------------- 14.7/14.7 MB 205.2 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
my_array = np.array([10,12,14,16,20,25])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int32
4


In [16]:
my_array = np.array(["Red", "Green", "Orange"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [20]:
my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [21]:
my_array3 = my_array.astype("M")
print(my_array3.dtype)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [31]:
# Officel Docs
x = np.arange(15, dtype=np.int64).reshape(3,5)

In [32]:
x[1:, ::2] = -99

In [33]:
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [34]:
x.max(axis=1)

array([ 4,  8, 13], dtype=int64)

In [35]:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([ 0.56749136,  0.75703316, -0.26728795, ...,  0.8023474 ,
        0.36606365, -0.85001431])

In [1]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray